### ISSUE TITLE
NPE when opening metar solution project.

### ISSUE THREAD

**Issue by fac2003** [CampagneLaboratory/MetaR#30]
java.lang.NullPointerException
	at org.campagnelab.editor.listeners.plugin.plugin.RegisteredListeners.add(Unknown Source)
	at org.campagnelab.editor.images.EditorCode.EditorCell_RefreshableImage.onAdd(Unknown Source)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.onAdd(EditorCell_Collection.java:982)
	at jetbrains.mps.nodeEditor.EditorComponent.setRootCell(EditorComponent.java:1579)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.doUpdate(UpdaterImpl.java:113)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.update(UpdaterImpl.java:88)
	at jetbrains.mps.nodeEditor.EditorComponent.rebuildEditorContent(EditorComponent.java:1850)
	at jetbrains.mps.nodeEditor.NodeEditorComponent.rebuildEditorContent(NodeEditorComponent.java:139)
	at jetbrains.mps.nodeEditor.EditorComponent$24.run(EditorComponent.java:1134)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:97)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
	at jetbrains.mps.nodeEditor.EditorComponent.editNode(EditorComponent.java:1098)
	at jetbrains.mps.ide.editor.BaseNodeEditor$1.performTask(BaseNodeEditor.java:108)
	at jetbrains.mps.ide.editor.BaseNodeEditor$PrioritizedTask.run(BaseNodeEditor.java:336)
	at jetbrains.mps.ide.editor.BaseNodeEditor.executeInEDT(BaseNodeEditor.java:123)
	at jetbrains.mps.ide.editor.BaseNodeEditor.editNode(BaseNodeEditor.java:101)
	at jetbrains.mps.ide.editor.NodeEditor.<init>(NodeEditor.java:36)
	at jetbrains.mps.ide.editor.MPSEditorOpener.createEditorFor(MPSEditorOpener.java:71)
	at jetbrains.mps.ide.editor.MPSFileNodeEditor.recreateEditor(MPSFileNodeEditor.java:302)
	at jetbrains.mps.ide.editor.MPSFileNodeEditor.initEditor(MPSFileNodeEditor.java:320)
	at jetbrains.mps.smodel.WorkbenchModelAccess$2.run(WorkbenchModelAccess.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:843)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:100)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
	at jetbrains.mps.ide.editor.MPSFileNodeEditor.<init>(MPSFileNodeEditor.java:121)
	at jetbrains.mps.ide.editor.MPSFileNodeEditorProvider.createEditor(MPSFileNodeEditorProvider.java:57)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$39(FileEditorManagerImpl.java:872)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:882)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:207)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:562)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressSynchronously(CoreProgressManager.java:396)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:76)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:312)
	at com.intellij.openapi.progress.ProgressManager.run(ProgressManager.java:192)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:402)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:187)
	at jetbrains.mps.workbench.recent.RecentMPSProjectsManager.doOpenProject(RecentMPSProjectsManager.java:54)
	at com.intellij.ide.ReopenProjectAction.actionPerformed(ReopenProjectAction.java:68)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$672(ActionMenuItem.java:304)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:905)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:284)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$669(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:113)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:123)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:109)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by fac2003** [comment]
Using MPS 3.4.3. Migrating PM_Retina project. Got warning that some modules were not migrated:

<html>Module Solution depends on module org.campagnelab.editor.listeners.plugin [solution], which is not in project and is not fully migrated.</html>
<html>Module Solution depends on module org.campagnelab.instantrefresh.plugin [solution], which is not in project and is not fully migrated.</html>
<html>Module Solution depends on module org.campagnelab.runR [solution], which is not in project and is not fully migrated.</html>
